/**
 * A Interface for dapps for dApp Registry
 */
export interface DAppInterface {
  /**
   * The name of the dApp. This is what is shown on listing
   */
  name: string
  /**
   * A detailed description of the dApp
   */
  description: string
  images?: {
    /**
     * A URL to the logo of the dApp. Should be square and 512x512 in PNG format
     */
    logo: string
    /**
     * A URL to the banner of the dApp. Should be 1920x1080 and in PNG format
     */
    banner: string
    /**
     * A list of URLs to the screenshots of the dApp. Should be 1284 x 2778 and in PNG format
     */
    screenshots: [string, ...string[]]
    [k: string]: unknown
  }
  /**
   * If this is in OpenSource, the URL of the repository
   */
  repoUrl?: string
  /**
   * A Unique ID for each dApp.
   */
  dappId: string
  /**
   * The min age of user who should access this dApp
   */
  minAge: number
  /**
   * Boolean to signify if the dApp is for mature audience
   */
  isForMatureAudience: boolean
  /**
   * Boolean to signify if the dApp developers have a moderation in place for the content posted/generated by the dApp or it's users
   */
  isSelfModerated: boolean
  /**
   * A string in ISO-639-1 which signifies the language of the dApp
   */
  language: string
  /**
   * The version of the dApp that is available on the dApp store
   */
  version: string
  /**
   * Boolean to signify if the dApp is listed on the dApp store
   */
  isListed: boolean
  /**
   * The date on which this dApp is listed on dApp store. This date can be a future date as well. This can not be in past.
   */
  listDate: string
  /**
   * A string signifying if the dApp is available on which platform - web, iOS, android
   */
  availableOnPlatform: [
    "ios" | "web" | "android",
    ...("ios" | "web" | "android")[]
  ]
  /**
   * A list of countries where the dApp is available or unavailable. If this is not present, the dApp is available everywhere. If this is present, then one of either allowedCountries or blockedCountries should be present. If both are present, then the dApp is available in allowedCountries and unavailable in blockedCountries. The name of countries should be in ISO-3661-1 Alpha-2 Code.
   */
  geoRestrictions?: {
    /**
     * A list of countries where the dApp is available
     */
    allowedCountries?: string[]
    /**
     * A list of countries where the dApp is unavailable
     */
    blockedCountries?: string[]
    [k: string]: unknown
  }
  developer: {
    /**
     * Legal name of the developer or the company
     */
    legalName: string
    /**
     * A URL to the logo of the developer or the company. Should be square and 512x512 in PNG format
     */
    logo: string
    website: string
    privacyPolicyUrl: string
    support: {
      url: string
      email?: string
      [k: string]: unknown
    }
    /**
     * The github ID of the developer
     */
    githubID: string
    [k: string]: unknown
  }
  tags: [string, ...string[]]
  chains: [number, ...number[]]
  /**
   * The category of the dApp. You can assign one category to your dApp. The category you select is particularly important for your app’s discoverability on the dApp Store. This will be the category in which the app appears when users browse the dApp Store or filter search results, and it determines placement on the dApps tab or Games
   */
  category:
    | "books"
    | "business"
    | "developer tools"
    | "education"
    | "entertainment"
    | "finance"
    | "food and drink"
    | "games"
    | "graphics and design"
    | "health and fitness"
    | "lifestyle"
    | "kids"
    | "magazines and newspapers"
    | "medical"
    | "music"
    | "navigation"
    | "news"
    | "photo and video"
    | "productivity"
    | "reference"
    | "shopping"
    | "social networking"
    | "sports"
    | "travel"
    | "utilities"
    | "weather"
  [k: string]: unknown
}


